[package]
name = "quanta"
version = "0.1.0"
authors = ["Lorxu <sam@dirkback.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vulkano = "0.16"
vulkano-win = "0.16"
vulkano-shaders = "0.16"
winit = "0.19.4"
